name: UpdateStatus
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  UpdateStatus:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'
      - name: Install all necessary packages from requirements.txt
        run: pip install -r requirements.txt
      - name: Run the scraper...
        run: python scrape.py 1
      - name: Deploy
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Status Update